### ISSUE TITLE
Existing color is too light

### ISSUE THREAD

**Issue by KamalSinghKhanna** [kunal-kushwaha/commclassroom#6]
As we can see in the team section that Team members bios are not visible the existing color is too light, maybe we can change it to some other color like black.

`.team .member p {
    padding-top: 8px;
    font-size: 14px;
    font-style: italic;
    color: #aaaaaa;
}
`
you can see this [here](https://github.com/kunal-kushwaha/commclassroom/blob/master/assets/css/style.css) on lines 980 to 985.

**Comment by kunal-kushwaha** [comment]
thanks
