### ISSUE TITLE
Shifting the code base to React js

### ISSUE THREAD

**Issue by harkiratsm** [kunal-kushwaha/commclassroom#7]
I have the idea of shifting the code base to Reactjs , As this would create a awareness of learning react and more & more people would be able to contribute to this Repo , I with this amazing community member can make it possible . Rest @kunal-kushwaha decision lie upon you . 
 

Regards 
Harkirat Singh
(Student at Community Classroom)

**Comment by kunal-kushwaha** [comment]
we are already working on it and will open issue soon
